development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/ps_developement.sqlite3

testing
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: db/ps_testing.sqlite3
